"""Added tables for quizzes and scores

Revision ID: 3c8b1a2711fe
Revises: e65163718cc8
Create Date: 2025-04-09 17:36:04.027786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8b1a2711fe'
down_revision = 'e65163718cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('scores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.Column('attempts', sa.INTEGER(), nullable=True),
    sa.Column('highest_score', sa.INTEGER(), nullable=False),
    sa.Column('lowest_score', sa.INTEGER(), nullable=False),
    sa.Column('last_score', sa.INTEGER(), nullable=False),
    sa.Column('last_attempt_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.Column('question_text', sa.TEXT(), nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('option_a', sa.VARCHAR(length=200), nullable=True),
    sa.Column('option_b', sa.VARCHAR(length=200), nullable=True),
    sa.Column('option_c', sa.VARCHAR(length=200), nullable=True),
    sa.Column('option_d', sa.VARCHAR(length=200), nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
