"""Add profile pic and learning goal to User table

Revision ID: 7ae095498c76
Revises: 9e29904f1022
Create Date: 2025-04-24 12:12:19.872339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae095498c76'
down_revision = '9e29904f1022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('learning_goal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('learning_goal')
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
