"""empty message

Revision ID: 801f5ea74388
Revises: e4607d42a8c6
Create Date: 2025-04-10 19:28:15.086885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801f5ea74388'
down_revision = 'e4607d42a8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
