"""Add achievements table

Revision ID: 9e29904f1022
Revises: 801f5ea74388
Create Date: 2025-04-18 17:42:26.690302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9e29904f1022'
down_revision = '801f5ea74388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic')
    op.drop_table('quiz_question')
    op.drop_table('quiz_questions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.Column('question_text', sa.TEXT(), nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('code_snippet', sa.TEXT(), nullable=True),
    sa.Column('options', sqlite.JSON(), nullable=True),
    sa.Column('correct_answer', sa.TEXT(), nullable=True),
    sa.Column('explanation', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.Column('question_text', sa.TEXT(), nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('code_snippet', sa.TEXT(), nullable=True),
    sa.Column('options', sqlite.JSON(), nullable=True),
    sa.Column('correct_answer', sa.TEXT(), nullable=True),
    sa.Column('explanation', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
