"""Add xp_earned and total_xp_earned to QuizScore

Revision ID: d675a0ae9a62
Revises: 7ae095498c76
Create Date: 2025-04-29 17:32:00.372553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd675a0ae9a62'
down_revision = '7ae095498c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_earned', sa.Integer()))
        batch_op.add_column(sa.Column('total_xp_earned', sa.Integer()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_scores', schema=None) as batch_op:
        batch_op.drop_column('total_xp_earned')
        batch_op.drop_column('xp_earned')
