"""Make changes to score history table

Revision ID: e4607d42a8c6
Revises: 3c8b1a2711fe
Create Date: 2025-04-09 21:42:38.192764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e4607d42a8c6'
down_revision = '3c8b1a2711fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_question')
    op.drop_table('quiz_score')
    with op.batch_alter_table('score_history', schema=None) as batch_op:
        batch_op.drop_column('time_taken')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_taken', sa.INTEGER(), nullable=True))

    op.create_table('quiz_score',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.Column('most_recent_score', sa.INTEGER(), nullable=False),
    sa.Column('highest_score', sa.INTEGER(), nullable=False),
    sa.Column('lowest_score', sa.INTEGER(), nullable=False),
    sa.Column('average_score', sa.FLOAT(), nullable=False),
    sa.Column('total_attempts', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.Column('question_text', sa.TEXT(), nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('code_snippet', sa.TEXT(), nullable=True),
    sa.Column('options', sqlite.JSON(), nullable=True),
    sa.Column('correct_answer', sa.TEXT(), nullable=True),
    sa.Column('explanation', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
